# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StockUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for StockUIKit
  pod 'LBTATools'
  pod 'Charts'

  target 'StockUIKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StockUIKitUITests' do
    # Pods for testing
  end

end
